[package]
name = "async-web-client"
version = "0.1.0"
edition = "2021"
description = "async web client helpers"
license = "Apache-2.0 OR MIT"

[dependencies]
http = "0.2.9"
futures = "0.3.28"
log = "0.4.17"
thiserror = "1.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version="0.3.4", features=['ReadableStream', 'ReadableStreamDefaultReader'] }
gloo-net = { version = "0.2.6", features = ["http"], default-features = false }
wasm-bindgen = "0.2.84"
js-sys = "0.3.61"
wasm-bindgen-futures = "0.4.34"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-http-codec = "0.5.6"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-logger = "0.2.0"
console_error_panic_hook = "0.1.7"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
smol = "1.3.0"

