[package]
name = "async-web-client"
version = "0.2.7"
edition = "2021"
description = "async web client helpers"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/FlorianUekermann/async-web-client"

[dependencies]
http = "0.2.9"
futures = "0.3.28"
log = "0.4.17"
thiserror = "1.0"
lazy_static = "1.4.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version="0.3.4", features=['ReadableStream', 'ReadableStreamDefaultReader'] }
gloo-net = { version = "0.2.6", features = ["http"], default-features = false }
wasm-bindgen = "0.2.84"
js-sys = "0.3.61"
wasm-bindgen-futures = "0.4.34"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-http-codec = "0.5.8"
async-net = "1.7.0"
futures-rustls = "0.24.0"
async-ws = "0.3.4"
webpki-roots = "0.25.1"
rustls = "0.21.6"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-logger = "0.2.0"
console_error_panic_hook = "0.1.7"
console_log = { version = "1", features = ["color"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
smol = "1.3.0"
env_logger = "0.10"
