[package]
name = "async-web-client"
version = "0.1.0"
edition = "2021"
description = "async web client helpers"
license = "Apache-2.0 OR MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
